week-4
Dev-incubator/DIMS.UI-16 pull request #11
Opened 2022-03-04 02:26 UTC by oleg3555

2022-03-20 14:52 UTC, Dev1LtJ requested changes
Hello! I left some comments.

2022-03-20 14:52 UTC, Dev1LtJ commented on src/App/App.jsx
> +          </Switch>
create function for routes generation.

2022-03-20 14:52 UTC, Dev1LtJ commented on src/App/header/Header.jsx
> +          </Navbar.Collapse>
Create links inside common `Nav` and `Navbar`.

2022-03-20 14:52 UTC, Dev1LtJ commented on src/pages/modals/trackModals/trackModalHelpers.js
> +  }
You have a lot of similar logic in your helpers. Let's merge it.

2022-03-20 14:52 UTC, Dev1LtJ commented on src/scripts/libraries.js
> +export const BUTTON_COLORS = {
move this file to /constants/... It's not a script

2022-03-20 14:52 UTC, Dev1LtJ commented on src/pages/members/Members.jsx
> +    this.isComponentMounted = true;
Why do you need it?

2022-03-22 15:39 UTC, oleg3555 commented on src/pages/modals/trackModals/trackModalHelpers.js
> +  }
Yeap, this function is like `getTaskModalErrors`. Replased to this 
in both functions:
```suggestion
  const keys = Object.keys(formErrors);
  keys.forEach((key) => {
    if (!state[key].trim()) {
      formErrors[key] = `${MODAL_VALUES[key]} is required`;
    }
  });
```

2022-03-22 16:21 UTC, oleg3555 commented on .idea/dims-cra.iml
> +    <orderEntry type="library" name="react-bootstrap" level="application" />
Fixed

2022-03-25 23:27 UTC, oleg3555 commented on src/App/App.jsx
> +          </Switch>
```suggestion
   const generateRoutes = () => {
    return (
      <div>
        <Route path='/about' exact component={About} />
        {user ? (
          <div>
            <Route path='/users' exact component={Members} />
            <Route path='/tasks' exact component={Tasks} />
            <Route path='/progress/:id' component={Progress} />
            <Route path='/tasks/:id' component={UserTasks} />
            <Route path='/track/:userId/:taskId' component={Tracks} />
          </div>
        ) : (
          <div>
            <Route path='/login' exact component={LogIn} />
          </div>
        )}
      </div>
    );
  };
```
Fixed

2022-03-25 23:48 UTC, oleg3555 commented on src/App/header/Header.jsx
> +          </Navbar.Collapse>
```suggestion
        <Navbar.Collapse id='responsive-navbar-nav'>
          <Nav className={`${styles.links} me-auto`}>
            {user && (
              <div className={styles.links}>
                <NavLink to='/users' activeClassName={styles.active}>
                  Members
                </NavLink>
                <NavLink to='/tasks' activeClassName={styles.active}>
                  Tasks
                </NavLink>
              </div>
            )}
            <NavLink to='/about' activeClassName={styles.active}>
              About
            </NavLink>
          </Nav>
          <Nav>
            {user ? (
              <div className={styles.auth}>
                <Navbar.Text>{userName}</Navbar.Text>
                <NavLink to='/login' onClick={logOut} activeClassName={styles.active}>
                  Log out
                </NavLink>
              </div>
            ) : (
              <NavLink to='/login' className={styles.logIn} activeClassName={styles.active}>
                Log In
              </NavLink>
            )}
          </Nav>
        </Navbar.Collapse>
```
Fixed

2022-03-27 20:00 UTC, maximsan requested changes
Hello! I left some comments. Please fix and ask questions if something unclear. Good work. Keep rolling! 😺

2022-03-27 20:20 UTC, oleg3555 commented on src/pages/modals/form/formSubmit/FormSubmit.jsx
> +export function FormSubmit({ disableModalMode, onSubmit, submitButtonColor, readOnly, submitButtonValue }) {
It has two buttons, one is cancel, second is submit

2022-03-28 14:06 UTC, oleg3555 commented on README.md
> +  "test:coverage:ci:codecov" - run helperTests and submit codecoverage to codecov
Auto refactor)) Fixed

2022-03-28 14:07 UTC, oleg3555 commented on package.json
> +    "bootstrap": "^5.1.3",
Fixed

2022-03-28 14:10 UTC, oleg3555 commented on src/components/Modal/Modal.jsx
> +        className={active ? `${styles.modalContent} ${styles.active}` : styles.modalContent}
```suggestion
        className={`${styles.modalContent} ${active ? styles.active : ''}`}
```
Fixed

2022-03-28 14:55 UTC, oleg3555 commented on src/App/App.jsx
> +  });
```suggestion
onAuthStateChanged(auth, (currentUser) => {
  localStorage.setItem('user', JSON.stringify(currentUser));
});

export const AuthContext = React.createContext({
  user: null,
  logOut: () => {},
  logIn: () => {},
});

class AuthProvider extends PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      userContext: {
        user: null,
        logIn: this.logIn,
        logOut: this.logOut,
      },
    };
    this.isUserDataSetted = false;
  }

  async componentDidMount() {
    await this.auth();
  }

  logOut = async () => {
    await signOut(auth);
    await this.auth();
  };

  logIn = async (email, password) => {
    const { history } = this.props;
    const error = await login(email, password);
    if (!error) {
      await this.auth();
      history.push('/about');
    }

    return error;
  };

  auth = async () => {
    const user = JSON.parse(localStorage.getItem('user'));
    this.isUserDataSetted = true;
    if (user) {
      const currentUser = await getUserById(user.uid);
      this.setState((prevState) => ({ userContext: { ...prevState.userContext, user: currentUser } }));
    } else {
      this.setState((prevState) => ({ userContext: { ...prevState.userContext, user } }));
    }
  };

  render() {
    const { userContext } = this.state;
    const { children } = this.props;
    if (!this.isUserDataSetted) {
      return null;
    }

    return <AuthContext.Provider value={userContext}>{children}</AuthContext.Provider>;
  }
}

AuthProvider.propTypes = {
  history: PropTypes.shape({ push: PropTypes.func.isRequired }).isRequired,
  children: PropTypes.node.isRequired,
};

export default withRouter(AuthProvider);
```
Fixed, made authProvider

2022-03-28 14:59 UTC, oleg3555 commented on src/pages/logIn/LogIn.jsx
> +    const reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
Fixed, we have been discussed it in another pull request, moved it to regulars file.

2022-03-28 15:02 UTC, oleg3555 commented on src/pages/logIn/LogIn.jsx
> +      this.setError(INPUT_NAMES.password, 'Password is too big');
```suggestion
 isFormValid = () => {
    const { email, password } = this.state;
    let formValid = false;
    if (password.length < 8) {
      this.setError(INPUT_NAMES.password, 'Password should contains 8 or more symbols');
    } else if (password.length > 24) {
      this.setError(INPUT_NAMES.password, 'Password is too long');
    } else {
      formValid = true;
    }

    if (!emailRegular.test(email)) {
      this.setError(INPUT_NAMES.email, 'Please, use correct email');
      formValid = false;
    }

    return formValid;
  };
```
Fixed, wrote method for this validation

2022-03-28 15:04 UTC, oleg3555 commented on src/pages/logIn/LogIn.jsx
> +      this.setError(INPUT_NAMES.email, 'Please, use correct email');
Fixed in comment  above

2022-03-28 15:34 UTC, oleg3555 commented on src/App/header/Header.jsx
> +  const userName = user && user.email ? user.email.split('@')[0] : '';
```suggestion
  const userName = getUserName(user);
```
Fixed

2022-03-28 15:41 UTC, maximsan commented on src/App/App.jsx
> +  });
logOut = async () => {
    await signOut(auth);
    await this.auth();
  }; - why do you call `this.auth()`??
  
  why do you need `isUserDataSetted ` ?
  
  method `auth` also looks pretty weird, you wrote strange logic.
   I'm also not sure that you need to keep `user` in local storage..

2022-03-28 15:42 UTC, oleg3555 commented on src/components/Toasts/ErrorToast.jsx
> +export function ErrorToast({ active, onClose }) {
```suggestion
ErrorToast.defaultProps = {
  message: 'Something went wrong, try again later!',
  delay: 5000,
};
```
Fixed

2022-03-28 15:42 UTC, oleg3555 commented on src/components/Toasts/ErrorToast.jsx
> +      <Toast.Body>Something went wrong, try again later!</Toast.Body>
```suggestion
ErrorToast.defaultProps = {
  message: 'Something went wrong, try again later!',
  delay: 5000,
};
```
Fixed

2022-03-28 15:49 UTC, oleg3555 commented on src/pages/modals/taskModals/helperTests/getTaskModalErrors.test.js
> +  expect(getTaskModalErrors(state1)).toEqual(false);
Fixed
```suggestion
  expect(getTaskModalErrors(state1)).toBeFalsy();
```

2022-03-28 16:16 UTC, oleg3555 commented on src/pages/modals/trackModals/tests/gatherTrackModalState.test.js
> +  expect(gatherTrackModalState(track, taskName)).toEqual(result);
Fixed

2022-03-28 16:18 UTC, oleg3555 commented on src/pages/modals/trackModals/tests/gatherTrackModalState.test.js
> +  expect(gatherTrackModalState(track, taskName)).toEqual(result);
```suggestion
  const taskName2 = 'Create smth';

  const result = {
    date: '2022-03-04',
    formErrors: { date: '', note: '' },
    modalTitle: 'Edit task track',
    note: 'dasaddas',
    readOnly: false,
    taskName: 'Create button',
  };
  expect(gatherTrackModalState(track, taskName)).toEqual(result);
  expect(gatherTrackModalState(track, taskName2)).not.toEqual(result);
```

2022-03-28 16:18 UTC, oleg3555 commented on src/pages/modals/taskModals/helperTests/getReadModalState.test.js
> +  expect(getReadModalState(task, users)).toEqual(result);
Fixed

2022-03-28 16:18 UTC, oleg3555 commented on src/pages/modals/taskModals/helperTests/getModalTaskData.test.js
> +  expect(getModalTaskData(state)).toEqual(result);
Fixed

2022-03-28 16:19 UTC, oleg3555 commented on src/pages/modals/taskModals/helperTests/getEditModalState.test.js
> +  expect(getEditModalState(task, users)).toEqual(result);
Fixed

2022-03-28 16:19 UTC, oleg3555 commented on src/pages/modals/taskModals/helperTests/getCreateModalState.test.js
> +  expect(getCreateModalState(users)).toEqual(result);
Fixed

2022-03-28 16:57 UTC, oleg3555 commented on src/App/App.jsx
> +  });
`
onAuthStateChanged(auth, (currentUser) => {
  localStorage.setItem('user', JSON.stringify(currentUser));
});

export const AuthContext = React.createContext({
  user: null,
  logOut: () => {},
  logIn: () => {},
});

class AuthProvider extends PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      userContext: {
        user: null,
        logIn: this.logIn,
        logOut: this.logOut,
      },
    };
    this.isUserDataSetted = false;
  }

  async componentDidMount() {
    await this.auth();
  }

  logOut = async () => {
    await signOut(auth);
    this.setState((prevState) => ({ userContext: { ...prevState.userContext, user: null } }));
  };

  logIn = async (email, password) => {
    const { history } = this.props;
    const error = await login(email, password);
    if (!error) {
      await this.auth();
      history.push('/about');
    }

    return error;
  };

  auth = async () => {
    const user = JSON.parse(localStorage.getItem('user'));
    this.isUserDataSetted = true;
    if (user) {
      const currentUser = await getUserById(user.uid);
      this.setState((prevState) => ({ userContext: { ...prevState.userContext, user: currentUser } }));
    }
  };

  render() {
    const { userContext } = this.state;
    const { children } = this.props;
    if (!this.isUserDataSetted) {
      return null;
    }

    return <AuthContext.Provider value={userContext}>{children}</AuthContext.Provider>;
  }
}
`
Is it better?

2022-03-28 17:28 UTC, maximsan requested changes
Hello! I left some more comments. Please adjust you code accordingly. Thanks!

2022-03-28 17:28 UTC, maximsan commented on src/components/Modal/Modal.jsx
> +      className={active ? `${styles.modal} ${styles.active}` : styles.modal}
why you didn't do the same here ?

2022-03-28 17:28 UTC, maximsan commented on src/pages/modals/taskModals/helperTests/getReadModalState.test.js
> +    expect(getReadModalState(task2, users)).not.toEqual(result);
Move every test-case in separate `it`

2022-03-28 17:28 UTC, maximsan commented on src/scripts/api-service.js
> +    return [];
you should not return any result from here except error, because it's failed. if you want to handle it somehow you should do it in component accordingly

2022-03-28 17:28 UTC, maximsan commented on src/tests/changeDataFormat.test.js
> +    expect(changeDateFormat(date2)).toEqual(date1);
one `it` with description for every different test

2022-03-29 13:01 UTC, oleg3555 commented on src/scripts/api-service.js
> +    return [];
Fixed to `return error;` in all same places

2022-03-31 17:04 UTC, maximsan requested changes
Please fix notes. Don't forget to remove 'package-lock.json' file

2022-03-31 17:04 UTC, maximsan commented on src/tests/changeDataFormat.test.js
> +    expect(changeDateFormat(date1)).toEqual(date2);
const actual = changeDateFormat('13.11.2020');

    expect(actual).toEqual('2020-11-13');

2022-03-31 22:06 UTC, oleg3555 commented on src/pages/modals/trackModals/tests/getTrackModalErrors.test.js
> +  it('Function should return that it is no errors in modal', () => {
Fixed at all tests

2022-03-31 22:08 UTC, oleg3555 commented on src/pages/modals/trackModals/tests/getTrackModalErrors.test.js
> +    expect(getTrackModalErrors(state)).toBeFalsy();
Fixed at tracks and tasks

2022-03-31 22:09 UTC, oleg3555 commented on src/tests/changeDataFormat.test.js
> +    expect(changeDateFormat(date1)).toEqual(date2);
```suggestion
describe('Helper functions tests', () => {
  it('Should change format of date', () => {
    const actual = changeDateFormat('13.11.2020');

    expect(actual).toEqual('2020-11-13');
  });

  it('Should check, that changing something at all', () => {
    const actual = changeDateFormat('2020-11-13');
    expect(actual).not.toEqual('2020-11-13');
  });
});

```
Fixed

2022-03-31 22:20 UTC, oleg3555 commented on src/App/App.jsx
> +  generateRoutes = () => {
```suggestion
export function GeneratedRoutes() {
  return (
    <AuthContext.Consumer>
      {({ user }) => (
        <>
          <Route path='/about' exact component={About} />
          {user ? (
            <>
              <Route path='/users' exact component={Members} />
              <Route path='/tasks' exact component={Tasks} />
              <Route path='/progress/:id' component={Progress} />
              <Route path='/tasks/:id' component={UserTasks} />
              <Route path='/track/:userId/:taskId' component={Tracks} />
            </>
          ) : (
            <Route path='/login' exact component={LogIn} />
          )}
        </>
      )}
    </AuthContext.Consumer>
  );
}
```
Fixed

2022-03-31 22:20 UTC, oleg3555 commented on src/App/App.jsx
> +          <div>
Fixed in comment above

2022-03-31 22:46 UTC, oleg3555 commented on src/App/App.jsx
> +App.contextType = AuthContext;
```suggestion
export const withAuthContext = (Component) => {
  return (props) => {
    return (
      <AuthContext.Consumer>
        {(context) => {
          return <Component {...props} context={context} />;
        }}
      </AuthContext.Consumer>
    );
  };
};
```

```suggestion
export default withAuthContext(Header);
```

Fixed using HOC

2022-03-31 23:43 UTC, oleg3555 commented on src/components/Modal/Modal.jsx
> +    document.getElementById('portal'),
```suggestion
export class Modal extends PureComponent {
  constructor(props) {
    super(props);
    this.root = document.createElement('div');
  }

  componentDidMount() {
    document.body.appendChild(this.root);
  }

  componentWillUnmount() {
    document.body.removeChild(this.root);
  }

  render() {
    const { active, disableModalMode, children } = this.props;

    return ReactDOM.createPortal(
      <div className={`${styles.modal} ${active ? styles.active : ''}`} onClick={disableModalMode} aria-hidden='true'>
        <div
          className={`${styles.modalContent} ${active ? styles.active : ''}`}
          onClick={(event) => event.stopPropagation()}
          aria-hidden='true'
        >
          {children}
        </div>
      </div>,
      this.root,
    );
  }
}
```
Fixed

2022-04-02 17:32 UTC, oleg3555 commented on src/scripts/api-service.js
> +    return null;
fixed to undefined

2022-04-05 07:10 UTC, maximsan commented on src/App/App.jsx
> +App.contextType = AuthContext;
Don't forget to add propTypes

2022-04-05 07:21 UTC, maximsan approved these changes
Ok. Let's move on. It's approved. Please get 1 more approve and merge it. Thanks! Good work!

2022-04-05 13:11 UTC, LeoKuD approved these changes
Good Job! Approve.

2022-04-05 13:11 UTC, merged