week-5
Dev-incubator/DIMS.UI-16 pull request #12
Opened 2022-03-12 03:34 UTC by oleg3555

2022-04-05 18:32 UTC, maximsan requested changes
Please remove package-lock.json file, reinstall all packages, fix notes. Thanks!

2022-04-05 18:32 UTC, maximsan commented on src/pages/modals/userModal/helperTests/getReadUserModalState.test.js
> +      address: 'Руссиянова 4',
Don't use Russian with English. Use only English !

2022-04-05 18:32 UTC, maximsan commented on src/pages/modals/userModal/userModalHelpers.js
> +export const initStartUserModalState = {
name it `userState` or `userModalState`

2022-04-05 18:32 UTC, maximsan commented on src/pages/modals/userModal/userModalHelpers.js
> +};
export const getUserModalState = (title, readOnly = false) => {
  return { ...initStartUserModalState, title, readOnly };
};
`getUserModalState(user, USER_MODAL_TITLES.edit)`

2022-04-05 18:32 UTC, maximsan commented on src/pages/setPassword/SetPassword.jsx
> +    if (password.length < 8 || password.length > 24) {
reuse this code

2022-04-05 18:32 UTC, maximsan commented on src/pages/setPassword/SetPassword.jsx
> +      return <div className={styles.wrapper}>Loading...</div>;
create <Loader /> component

2022-04-05 18:32 UTC, maximsan commented on src/pages/setPassword/SetPassword.jsx
> +            {error && <div className={styles.error}>Password should contains 8-24 symbols</div>}
create `<Error />` component

2022-04-05 18:32 UTC, maximsan commented on src/pages/tasks/Tasks.jsx
> +    });
const newTask = { ...updatedTask, users: updatedUsers }

2022-04-05 18:32 UTC, maximsan commented on src/tests/getAge.test.js
> +describe('Helper functions tests', () => {
`getAge`

2022-04-05 18:32 UTC, maximsan commented on src/tests/getUserName.test.js
> +describe('Helper functions tests', () => {
`getUserName`

2022-04-05 18:32 UTC, maximsan commented on src/pages/members/Members.jsx
> +        <PageHeader text={PAGE_TITLES.members} onClick={() => this.setModalMode(MODAL_MODES.create)} />
create handler

2022-04-05 18:32 UTC, maximsan commented on src/pages/members/Members.jsx
> +            disableModalMode={this.disableModalMode}
`close` or `onClose` if it closes modal

2022-04-05 18:32 UTC, maximsan commented on src/pages/members/Members.jsx
>              removeHandler={this.removeUser}
`onRemove` or `onDelete`

2022-04-06 00:01 UTC, oleg3555 commented on src/pages/modals/form/formField/FormField.jsx
> +            placeholder={fieldName}
Fixed

2022-04-06 00:01 UTC, oleg3555 commented on src/pages/modals/form/formField/FormField.jsx
> +              {fieldName}
Fixed

2022-04-06 00:02 UTC, oleg3555 commented on src/pages/modals/form/formField/FormField.jsx
> +export function FormField({ onChange, inputValue, fieldName, readOnly, stylingType, inputName, error, selectValues }) {
Created 2 components, `<Input/>` and `<Select/>`

2022-04-06 00:06 UTC, oleg3555 commented on src/pages/modals/taskModals/taskForm/TaskModalUsersList.jsx
> +                    text={`${user.name} ${user.surname}`}
```suggestion
export const getFullName = (name, surname) => {
  return `${name} ${surname}`;
};
```
Fixed

2022-04-06 00:06 UTC, oleg3555 commented on src/pages/modals/userModal/helperTests/getReadUserModalState.test.js
> +      address: 'Руссиянова 4',
Fixed

2022-04-06 00:14 UTC, oleg3555 commented on src/pages/modals/userModal/userModalHelpers.js
> +export const initStartUserModalState = {
Fixed

2022-04-06 00:16 UTC, oleg3555 commented on src/pages/modals/userModal/userModalHelpers.js
> +  modalTitle: '',
Fixed

2022-04-06 00:16 UTC, oleg3555 commented on src/pages/modals/userModal/userModalHelpers.js
> +  formErrors: {
Fixed

2022-04-06 00:16 UTC, oleg3555 commented on src/pages/modals/userModal/userModalHelpers.js
> +  const formErrors = { ...formFields };
Fixed

2022-04-06 00:22 UTC, oleg3555 commented on src/pages/modals/userModal/userModalHelpers.js
> +  return { ...initStartUserModalState, ...user, modalTitle: USER_MODAL_TITLES.read, readOnly: true };
Fixed

2022-04-06 01:10 UTC, oleg3555 commented on src/pages/modals/userModal/userModalHelpers.js
> +};
```suggestion
const getModalTitle = (user, readOnly) => {
  if (readOnly && user) {
    return USER_TITLES.read;
  }
  if (user) {
    return USER_TITLES.edit;
  }

  return USER_TITLES.read;
};

export const getUserModalState = (user = null, readOnly = false) => {
  const title = getModalTitle(user, readOnly);

  return { ...userModalState, ...user, title, readOnly };
};
```
And remove 3 mrthods from UserModal.jsx and looks better, thanks
```suggestion
componentDidMount() {
    const { user, readOnly } = this.props;
    const data = getUserModalState(user, readOnly);
    this.setState(data);
  }
```

2022-04-06 01:19 UTC, oleg3555 commented on src/pages/modals/userModal/userModalHelpers.js
> +};
Rewatched my other modal helpers, and I'm not reusing it

2022-04-06 01:20 UTC, oleg3555 commented on src/pages/setPassword/SetPassword.jsx
> +            {error && <div className={styles.error}>Password should contains 8-24 symbols</div>}
Done)

2022-04-06 01:22 UTC, oleg3555 commented on src/tests/getAge.test.js
> +describe('Helper functions tests', () => {
Fixed

2022-04-06 01:22 UTC, oleg3555 commented on src/tests/getUserName.test.js
> +describe('Helper functions tests', () => {
Fixed

2022-04-06 01:27 UTC, oleg3555 commented on src/pages/members/Members.jsx
> +        <PageHeader text={PAGE_TITLES.members} onClick={() => this.setModalMode(MODAL_MODES.create)} />
```suggestion
<PageHeader text={PAGE_TITLES.members} onClick={this.setModalMode} />
```
And in setModalMode I set it as default parametr
```suggestion
setModalMode = (modalMode = MODAL_MODES.create, actionUserId = null) => {
    this.setState({ modalMode, actionUserId });
  };
```
Is it ok?

2022-04-06 02:01 UTC, oleg3555 commented on src/pages/tasks/Tasks.jsx
> +    });
Fixed

2022-04-06 02:04 UTC, oleg3555 commented on src/pages/members/Members.jsx
>              removeHandler={this.removeUser}
Fixed

2022-04-06 22:49 UTC, oleg3555 commented on src/pages/setPassword/SetPassword.jsx
> +    const id = encryptId(cryptedId);
const id = getUid(document.location.search);
And in helper
```suggestion
export function getUid(url) {
  const idParameter = 'uid%3D';
  const cryptedId = url.substring(url.indexOf(idParameter) + idParameter.length, url.indexOf('&lang'));

  return encryptId(cryptedId);
}
```
Is  it ok?

2022-04-07 00:50 UTC, oleg3555 commented on src/pages/setPassword/SetPassword.jsx
> +    if (password.length < 8 || password.length > 24) {
Created method
```suggestion
export const isPasswordValid = (password) => {
  return password.length >= 8 && password.length <= 24;
};
```

2022-04-07 01:17 UTC, oleg3555 commented on src/pages/setPassword/SetPassword.jsx
> +      return <div className={styles.wrapper}>Loading...</div>;
Fixed

2022-04-07 03:33 UTC, oleg3555 commented on src/pages/members/Members.jsx
>              removeHandler={this.removeUser}
Fixed

2022-04-07 03:33 UTC, oleg3555 commented on src/pages/members/Members.jsx
> +            disableModalMode={this.disableModalMode}
Fixed

2022-04-12 14:20 UTC, oleg3555 commented on src/pages/setPassword/SetPassword.jsx
> +    const id = encryptId(cryptedId);
`export function getUid(url) {
  const cryptedId = url.match(cryptedIdRegular).pop();

  return encryptId(cryptedId);
}`

`cryptedIdRegular = /[0-9]+(a[0-9]+)+/g;`

Fixed

2022-04-12 14:27 UTC, maximsan approved these changes
Looks fine. I left a comment. Don't forget to add tests for methods you forgot to cover. It's approved 🚀

2022-04-12 14:30 UTC, maximsan requested changes
Pardon, but where is theme switcher ? Please add a user into pr description I can use to login

2022-04-12 14:40 UTC, maximsan approved these changes

2022-04-13 04:33 UTC, merged