week-6
Dev-incubator/DIMS.UI-16 pull request #13
Opened 2022-03-19 11:04 UTC by oleg3555

2022-04-14 14:28 UTC, maximsan requested changes
Hello! I left some comments. BTW where is redux integration or I missed something? ))

2022-04-14 14:28 UTC, maximsan commented on src/App/App.jsx
> +          <div className={styles.App} style={{ backgroundColor: theme.backgroundColor }}>
this approach is not good, use class for theme or find another approach but not this one 😉

2022-04-17 06:47 UTC, oleg3555 commented on package.json
> +    "eslint-config-react-app": "^7.0.1",
It was eslint errors until I add this

2022-04-17 06:47 UTC, oleg3555 commented on src/App/App.jsx
> +          <div className={styles.App} style={{ backgroundColor: theme.backgroundColor }}>
Fixed

2022-04-19 09:09 UTC, maximsan commented on package.json
> +    "eslint-config-react-app": "^7.0.1",
it's because you installed dependencies wrongly, but let's skip it for now

2022-04-19 09:33 UTC, maximsan requested changes
Hello! I left some comments. Please fix them. The most urgent is the store using, please pay attention 😉

2022-04-19 09:33 UTC, maximsan commented on src/App/GeneratedRoutes.jsx
> +              <Route path='/tasks/:id' render={({ match }) => <UserTasks match={match} />} />
You have access to match by default inside props. Why do you do it like this ? There is a mistake somewhere in your integration

2022-04-19 09:33 UTC, maximsan commented on src/components/Buttons/Button/Button.jsx
> +};
You overcomplicate it here. Think how to simplify it via css classes.

2022-04-19 09:33 UTC, maximsan commented on src/pages/modals/form/ModalFields/Input/Input.jsx
> +    onChange(target.name, target.value);
scpread target

2022-04-19 09:33 UTC, maximsan commented on src/pages/tasks/Tasks.jsx
> +    error: state.fetch.error,
`fetch` field is redundant, make it simple

2022-04-19 09:33 UTC, maximsan commented on src/pages/tasks/Tasks.jsx
> +    addTask: (task) => dispatch(addTaskThunk(task)),
use `bindActionCreators` to concise your code

2022-04-19 09:33 UTC, maximsan commented on src/redux/fetchReducer/fetchReducer.js
> +export const enableLoaderAC = () => ({ type: ENABLE_LOADER });
`AC` part in name looks weird, I'd rather recommend to not add it at all

2022-04-19 09:33 UTC, maximsan commented on src/redux/tasksReducer/tasksReducer.js
> +      return [...state, { id: action.payload.id, ...action.payload.task }];
just pass a task object

2022-04-19 09:33 UTC, maximsan commented on src/redux/tasksThunk/tasksThunk.js
> +    const tasks = await getAllTasks();
do you handle possible errors ?

2022-04-19 09:33 UTC, maximsan commented on src/redux/tasksThunk/tasksThunk.js
> +      .then((doc) => dispatch(addTaskAC(doc.id, task)))
Let's stick to one way. Please use `Promise chaining` or `async wait` everywhere.

2022-04-19 09:33 UTC, maximsan commented on src/redux/usersReducer/usersReducer.js
> +// eslint-disable-next-line default-param-last
Do you need it ? It's better to change you code to avoid disabling of extra eslint rules

2022-04-19 15:42 UTC, oleg3555 commented on src/App/GeneratedRoutes.jsx
> +              <Route path='/tasks/:id' render={({ match }) => <UserTasks match={match} />} />
Fixed

2022-04-19 15:42 UTC, oleg3555 commented on src/App/GeneratedRoutes.jsx
> +                  <Route path='/tasks' exact render={() => <Tasks store={store} />} />
Fixed

2022-04-19 15:49 UTC, oleg3555 commented on src/pages/modals/form/ModalFields/Input/Input.jsx
> +    onChange(target.name, target.value);
Fixed

2022-04-19 15:53 UTC, oleg3555 commented on src/redux/tasksThunk/tasksThunk.js
> +    const tasks = await getAllTasks();
It is try catch block inside `getAllTasks` method

2022-04-19 15:56 UTC, oleg3555 commented on src/redux/usersReducer/usersReducer.js
> +// eslint-disable-next-line default-param-last
```suggestion
export const tasksReducer = (state = initialState, action = {}) => {
```
Fixed

2022-04-19 16:13 UTC, oleg3555 commented on src/redux/fetchReducer/fetchReducer.js
> +export const enableLoaderAC = () => ({ type: ENABLE_LOADER });
Fixed

2022-04-19 17:06 UTC, oleg3555 commented on src/components/Buttons/Button/Button.jsx
> +};
Fixed

2022-04-19 17:10 UTC, oleg3555 commented on src/redux/tasksThunk/tasksThunk.js
> +      .then((doc) => dispatch(addTaskAC(doc.id, task)))
Rewrote to async await

2022-04-19 17:34 UTC, oleg3555 commented on src/pages/tasks/Tasks.jsx
> +    error: state.fetch.error,
Fixed

2022-04-19 19:19 UTC, maximsan approved these changes
Hi! Well done. Approved!

2022-04-20 09:16 UTC, LeoKuD approved these changes
Good job. Have a good week.

2022-04-20 20:29 UTC, merged