Week 3
Dev-incubator/DIMS.UI-16 pull request #6
Opened 2022-02-28 22:29 UTC by oleg3555

Created page of members, member tasks, member progress. Now in app you can see:

1. tasks of selected user
2. user info in members table
3. data is in firestore
4. progress page
5. tasks page
6. you can delete user
7. subtasks of every user
8. delete task tracks
9. delete users
10. add tasks

2022-03-13 12:55 UTC, maximsan requested changes
Hello! I left some comments. Please review, fix, update and let me know when it's ready. Thanks!

2022-03-13 12:55 UTC, maximsan commented on .idea/dims-cra.iml
> +    <orderEntry type="library" name="react-bootstrap" level="application" />
please ignore the changes, you don't need to commit your specific IDE setup

2022-03-13 12:55 UTC, maximsan commented on src/App/App.jsx
> +        <span className={styles.copyright}>© Dev Incubator</span>
Create method for it and cover with unit tests. Name can be passed as a parameter and in general everything should be flexible, but not hard-coded

2022-03-13 12:55 UTC, maximsan commented on src/App/header/Header.jsx
> +      </NavLink>
it can be rewritten by using `map` if you use nav links as items. please fix it )

2022-03-13 12:55 UTC, maximsan commented on src/components/Checkbox/Checkbox.jsx
> +      <input type='checkbox' autoComplete='off' id={id} checked={value} onChange={onChange} />
pass `autoComplete` as a parameter set to 'off' by default

2022-03-13 12:55 UTC, maximsan commented on src/pages/modals/createModals/taskModal/TaskModal.jsx
> +            name: user.name,
create method `mapUsersTo....`

2022-03-13 12:55 UTC, maximsan commented on src/pages/modals/createModals/taskModal/TaskModal.jsx
> +    this.setState({ deadline: value });
pass name as s parameter, use 1 method instead

2022-03-13 12:55 UTC, maximsan commented on src/pages/modals/form/formField/FormField.jsx
> +          onFocus={() => this.setType(INPUT_TYPES.date)}
create handler method

2022-03-13 12:55 UTC, maximsan commented on src/pages/modals/form/formField/FormField.jsx
> +          onChange={(event) => onChange(event.currentTarget.value)}
create handler method, you can spread event inside handler

2022-03-15 14:31 UTC, oleg3555 commented on src/pages/modals/form/formField/FormField.jsx
> +          onChange={(event) => onChange(event.currentTarget.value)}
```suggestion
export function FormField({ onChange, placeholder, inputValue, fieldName, readOnly, stylingType, inputName, error }) {
  const onChangeHandler = ({ target: { name, value } }) => {
    onChange(name, value);
  };

  return (
    <div className={styles.formField}>
      <div className={styles.fieldName}>{fieldName}</div>
      <div>
        <input
          type={stylingType}
          disabled={readOnly}
          name={inputName}
          className={styles.input}
          placeholder={placeholder}
          value={inputValue}
          onChange={onChangeHandler}
        />
        {error && <div className={styles.errorMessage}>{error}</div>}
      </div>
    </div>
  );
}
```
Rewrite this component

2022-03-15 14:34 UTC, oleg3555 commented on src/components/Checkbox/Checkbox.jsx
> +      <input type='checkbox' autoComplete='off' id={id} checked={value} onChange={onChange} />
```suggestion
Checkbox.defaultProps = {
  autoComplete: 'off',
};
```
Fixed

2022-03-15 14:38 UTC, oleg3555 commented on src/pages/modals/createModals/taskModal/TaskModal.jsx
> +    this.setState({ deadline: value });
```suggestion
onChangeInputValue = (name, value) => {
    this.setState({ [name]: value });
  };
```
Fixed

2022-03-15 14:48 UTC, oleg3555 commented on src/App/header/Header.jsx
> +      </NavLink>
```suggestion
 {headerValues.map((item, index) => (
        <NavLink key={index.toString() + item} to={`/${item.toLowerCase()}`} activeClassName={styles.active}>
          {item}
        </NavLink>
      ))}
```
Fixed

2022-03-15 14:49 UTC, oleg3555 commented on .idea/dims-cra.iml
> +    <orderEntry type="library" name="react-bootstrap" level="application" />
I dont know why, file .idea is already in .gitignore

2022-03-17 12:55 UTC, oleg3555 commented on .idea/dims-cra.iml
> +    <orderEntry type="library" name="react-bootstrap" level="application" />
Fixed

2022-03-17 12:55 UTC, oleg3555 commented on src/App/App.jsx
> +        <span className={styles.copyright}>© Dev Incubator</span>
```suggestion
        <span className={styles.copyright}>{COPYRIGHT}</span>
```
Fixed

2022-03-21 05:59 UTC, maximsan approved these changes
Hello! Ok, it's fine in general, but where are your unit-tests and error handling in your API(firebase) methods ? 😄

2022-03-21 14:24 UTC, LeoKuD approved these changes
looks fine!

2022-03-21 17:27 UTC, merged